### ISSUE TITLE
Menentukan Ide Project Web

### ISSUE THREAD

**Issue by pieterch7** [pieterch7/uas-menpro#1]

**Comment by pieterch7** [comment]
Kira-kira kita akan membuat apa?

**Comment by stevenval12** [comment]
buat website komunitas gmn?

**Comment by felixwiranata1233** [comment]
mungkin kita membuat website komunitas foodwasted

**Comment by pieterch7** [comment]
@stevenval12 @felixwiranata1233  baiklah saya tentukan kita akan membuat website komunitas foodwasted

**Comment by stevenval12** [comment]
![Image](https://github.com/pieterch7/uas-menpro/assets/151891133/c342466f-4115-40bf-9e28-d450fee4e978)
