### ISSUE TITLE
Merancang file index.html

### ISSUE THREAD

**Issue by pieterch7** [pieterch7/uas-menpro#4]

**Comment by pieterch7** [comment]
kira-kira di dalam file index.html mau ada fitur apa saja?

**Comment by felixwiranata1233** [comment]
apa mungkin kita berikan navbar?

**Comment by stevenval12** [comment]
sepertinya bisa dibuat navbar yang responsif juga

**Comment by stevenval12** [comment]
<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="#page-top">Food waste</a>
                <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#portfolio">Portfolio</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#about">About</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>

nih dibikin responsive :v

**Comment by pieterch7** [comment]
kita juga akan menggunakan navbar juga

**Comment by pieterch7** [comment]
@felixwiranata1233 @stevenval12  baiklah saya terima ide-idenya
