### ISSUE TITLE
Membuat file index.html

### ISSUE THREAD

**Issue by pieterch7** [pieterch7/uas-menpro#5]

**Comment by pieterch7** [comment]
nanti kalian coba berkolaborasi di file index.html

**Comment by stevenval12** [comment]
oke

**Comment by felixwiranata1233** [comment]
disini aku ada ide menambahkan footnote

**Comment by pieterch7** [comment]
nanti footnote nya dikasih style biar rapih

**Comment by felixwiranata1233** [comment]
saya ada saran membuat icon hamburger ketika tampilannya mengecil

**Comment by pieterch7** [comment]
oo mungkin navbarnya dibuat hamburger ketika kecil

**Comment by pieterch7** [comment]
baiklah ide yang bagus

**Comment by pieterch7** [comment]
oke file index.html telah selesai
